### ISSUE TITLE
Pandas dropna/isna is not working properly in float columns pandas 2.1.0

### ISSUE THREAD

**Issue by mdavidg** [conda-forge/pandas-feedstock#105]
- I've just upgrade Big Sur 11.0.1 and I'm facing some issue. Could anyone help ?

Issue:
Applying dropna/isna functions to DataFrame/Series. I've noted when the column is type 'object' it works properly.
Example:
df = pd.DataFrame([np.nan, 7, 5.5])
df.isna()

I get as result:
False
False
False

Example2:
df = pd.DataFrame([np.nan, 7, 5.5])
df.dropna()

I get as result the same DataFrame/Series:
Nan
7.0
5.5

**Comment by h-vetinari** [comment]
Your example works for me:
```
>>> df = pd.DataFrame([np.nan, 7, 5.5], columns=['a'])
>>> df
     a
0  NaN
1  7.0
2  5.5
>>> df.dropna()
     a
1  7.0
2  5.5
```

You should probably try `conda update pandas` and see if something happens, and if not, raise this issue (according to the issue template) at https://github.com/pandas-dev/pandas/

**Comment by mdavidg** [comment]
Great, conda update pandas solved the problem. Thx
