### ISSUE TITLE
Test failures with NumPy 1.24

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/pandas-feedstock#150]
Seeing test failures on `main` like the following (taken from [this build]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=637552&view=logs&jobId=6920d3d3-ef74-5584-b309-e8e970b1eb3b&j=bb1c2637-64c6-57bd-9ea6-93823b2df951&t=350df31b-3291-5209-0bb7-031395f0baa1&s=96ac2280-8cb4-5df5-99de-dd2da759617d ) also [attached log]( https://github.com/conda-forge/pandas-feedstock/files/10376394/pandas_linux_64_numpy1.21python3.10.____cpythonpython_implcpython_20230106.1.txt )):

```python
<tests>/extension/test_sparse.py::TestReshaping::test_stack[0-columns0]
<tests>/extension/test_sparse.py::TestReshaping::test_stack[0-columns1]
<tests>/extension/test_sparse.py::TestMissing::test_fillna_limit_pad[0]
<tests>/extension/test_sparse.py::TestMissing::test_fillna_limit_backfill[0]
<tests>/extension/test_sparse.py::TestMissing::test_fillna_no_op_returns_copy[0]
<tests>/extension/test_sparse.py::TestMissing::test_fillna_series_method[0]
<tests>/frame/methods/test_sort_values.py::TestDataFrameSortValues::test_sort_values_sparse_no_warning[uint8]
<tests>/frame/methods/test_sort_values.py::TestDataFrameSortValues::test_sort_values_sparse_no_warning[bool]
<tests>/series/test_constructors.py::TestSeriesConstructors::test_constructor_signed_int_overflow_deprecation
```

Based on discussion offline with @mroeschke, these appear to be due to recent NumPy deprecations.

Note: This resulted in most of the CPython packages from PR ( https://github.com/conda-forge/pandas-feedstock/pull/147 ) not being published.

**Comment by jakirkham** [comment]
Constraining to NumPy 1.23 or earlier in the test phase ( https://github.com/conda-forge/pandas-feedstock/pull/151 ). Should workaround this issue

**Comment by mroeschke** [comment]
The test failures will be fixed in https://github.com/pandas-dev/pandas/pull/49886 and https://github.com/pandas-dev/pandas/pull/50686 which will hopefully be reflected the pandas 1.5.3 release fairly soon
