### ISSUE TITLE
256sum of source tarball doesn't match

### ISSUE THREAD

**Issue by lexual** [conda-forge/pandas-feedstock#18]
$ sha256sum v0.19.2.tar.gz 
    af634dd6ed3ca1f8635183f41e7f7769108531ccca8213067d9627857461702e  v0.19.2.tar.gz

The recipe says it should be:

wget https://github.com/pydata/pandas/archive/v0.19.2.tar.gz

    dd2ee30e21804675a6ef41bea854a023b8be3b840fd2aa33e7e1cc38066e781c

**Comment by jorisvandenbossche** [comment]
@lexual That seems indeed the case, so it seems that github has changed the tar slightly (I already noticed that updating the release notes can trigger that, although I cannot remember doing this this time). 
But is that a problem? We only need to update it when we need to rebuild the conda packages for some reason.
