### ISSUE TITLE
Is it possible to create a v1.5.x branch for Python 3.12 compatibility?

### ISSUE THREAD

**Issue by admirito** [conda-forge/pandas-feedstock#184]
### Comment:

I've got a quick question for the awesome folks behind pandas-feedstock project on conda-forge. I was wondering if it would be possible to create a v1.5.x branch to enable compatibility with Python 3.12.

Just recently, I had a fantastic experience on a rebuild [PR](https://github.com/conda-forge/pydantic-feedstock/pull/107) for the pydantic project. Now I'm keen to send a pull request that ensures the latest version within the 1.x release range of pandas aslo works with Python 3.12.

I've already created the branch with a new commit [here](https://github.com/admirito/pandas-feedstock/tree/v1.5.x-python3.12). So, could you consider creating a branch based on [66ac579](https://github.com/conda-forge/pandas-feedstock/tree/66ac579) for this purpose?

**Comment by ocefpaf** [comment]
Done!
