### ISSUE TITLE
Building with NumPy 2.0.0rc1

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/pandas-feedstock#204]
NumPy 2.0.0 is in the process of being released (currently on 2.0.0rc1) with a number of changes ( https://github.com/numpy/numpy/issues/24300 ). Most notably the way we build with NumPy may need changes. This will involve building with the latest NumPy and then configuring builds to support older NumPy versions (and validating binaries target the intended NumPy version)

There is some discussion about this in issue ( https://github.com/conda-forge/numpy-feedstock/issues/311 ) along with details on how to test builds with NumPy 2.0.0rc1. The next step to take here would be to try building the Pandas packages with NumPy 2.0.0rc1

Not sure what the state of Pandas support for NumPy 2 is (and whether we need an RC or new fixes). So getting a better idea on what is still needed on the Pandas side would help

**Comment by jakirkham** [comment]
> Not sure what the state of Pandas support for NumPy 2 is (and whether we need an RC or new fixes). So getting a better idea on what is still needed on the Pandas side would help

Maybe Pandas 2.2.2 is the version to target?

xref:
* https://github.com/pandas-dev/pandas/issues/55519
* https://github.com/pandas-dev/pandas/issues/58104
* https://github.com/pandas-dev/pandas/pull/58093

**Comment by lithomas1** [comment]
Yep. 

I messed up the PR building with numpy 2.0, so pandas-dev/pandas#55519 needs a redo, but expect a pandas 2.2.2 release soonish.

**Comment by lithomas1** [comment]
@jakirkham 
Just FYI,
pandas 2.2.2 should be out now with full numpy 2.0 compat.

**Comment by jakirkham** [comment]
Thanks Thomas! 🙏

**Comment by jakirkham** [comment]
Axel put together a NumPy 2 PR: https://github.com/conda-forge/pandas-feedstock/pull/207
