### ISSUE TITLE
pandas 2.2.x doesn't pin numpy >= 1.22.4

### ISSUE THREAD

**Issue by pgunn** [conda-forge/pandas-feedstock#208]
Pandas 2.2.x apparently needs numpy 1.22.4 but the feedstock wasn't updated.

```
​​>>> import pandas
​​...
​​ImportError: this version of pandas is incompatible with numpy < 1.22.4
​​your numpy version is 1.21.6.
​​Please upgrade numpy to >= 1.22.4 to use this pandas version
```

**Comment by pgunn** [comment]
(what I mean is that because the feedstock's metadata doesn't include a pin, the user can end up with an invalid permutation of pandas and numpy, such as numpy 1.21.6 and pandas 2.x)

**Comment by rootsmusic** [comment]
Pull #211
