### ISSUE TITLE
Large package size

### ISSUE THREAD

**Issue by mrocklin** [conda-forge/pandas-feedstock#54]
Uncompressed this package is around 100MB.  For comparison the package on defaults is around 40MB

```
conda create -n size-pandas-defaults -c defaults pandas nomkl
conda create -n size-pandas -c conda-forge pandas nomkl

$ du -s size-pandas/lib/python3.7/site-packages/* | sort -nr | head -5
106084	size-pandas/lib/python3.7/site-packages/pandas
19676	size-pandas/lib/python3.7/site-packages/numpy
8532	size-pandas/lib/python3.7/site-packages/pip
2772	size-pandas/lib/python3.7/site-packages/pytz
2172	size-pandas/lib/python3.7/site-packages/setuptools

$ du -s size-pandas-defaults/lib/python3.7/site-packages/* | sort -nr | head -5
42436	size-pandas-defaults/lib/python3.7/site-packages/pandas
19592	size-pandas-defaults/lib/python3.7/site-packages/numpy
8388	size-pandas-defaults/lib/python3.7/site-packages/pip
2772	size-pandas-defaults/lib/python3.7/site-packages/pytz
2172	size-pandas-defaults/lib/python3.7/site-packages/setuptools
```

**Comment by jorisvandenbossche** [comment]
I suppose it is the same as for the wheels: https://github.com/pandas-dev/pandas/issues/19531, https://github.com/MacPython/pandas-wheels/issues/24

But isn't this something that could/should be done by conda-forge in general, and not specific in the pandas recipe?

**Comment by mrocklin** [comment]
Yes perhaps.  I've also pointed some of the conda-forge maintainers here.

This doesn't affect all packages though, just some.  Pandas and OpenBLAS
were two of the largest offenders that I ran into.

**Comment by juandiegopalomino** [comment]
@mrocklin I too am running into this issue of ~100 mb pandas and openblas conda forge installations. Have you, or the maintainers, been able to resolve either of these packages' size issues?

**Comment by ocefpaf** [comment]
I just re-tried this and I cannot reproduce the same number. Actually, conda-forge is smaller now. I used strict and had one channel at a time on my `.condarc`.

conda create -n size-pandas-defaults -c defaults pandas nomkl
conda create -n size-pandas-conda-forge -c conda-forge pandas

Total:

```
245M    size-pandas-defaults
229M    size-pandas-conda-forge
```

top 5

```
> \du -s size-pandas-defaults/lib/python3.7/site-packages/* | sort -nr | head -5                     
48660   size-pandas-defaults/lib/python3.7/site-packages/pandas
20252   size-pandas-defaults/lib/python3.7/site-packages/numpy
8720    size-pandas-defaults/lib/python3.7/site-packages/pip
2776    size-pandas-defaults/lib/python3.7/site-packages/pytz
2212    size-pandas-defaults/lib/python3.7/site-packages/setuptools
```
```
> du -s size-pandas-conda-forge/lib/python3.7/site-packages/* | sort -nr | head -5
48604   size-pandas/lib/python3.7/site-packages/pandas
20084   size-pandas/lib/python3.7/site-packages/numpy
8720    size-pandas/lib/python3.7/site-packages/pip
2776    size-pandas/lib/python3.7/site-packages/pytz
2212    size-pandas/lib/python3.7/site-packages/setuptools
```

This is probably due to the new blas scheme that @isuruf implemented some time ago.
