### ISSUE TITLE
conda install pandas installs an rc candidate

### ISSUE THREAD

**Issue by moorepants** [conda-forge/pandas-feedstock#56]
Issue:

I would except `conda install -c conda-forge pandas` to install the latest release that is not a beta, alpha, rc, etc. Currently 0.24.0rc1 gets installed into my environment and seems to have some breaking features.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
moorepants@garuda:teamo(master)$ conda list pandas
# packages in environment at /home/moorepants/miniconda3:
#
# Name                    Version                   Build  Channel
pandas                    0.24.0rc1        py36hfc679d8_0    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
moorepants@garuda:teamo(master)$ conda info

     active environment : None
       user config file : /home/moorepants/.condarc
 populated config files : /home/moorepants/.condarc
          conda version : 4.5.12
    conda-build version : 3.16.3
         python version : 3.6.7.final.0
       base environment : /home/moorepants/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          http://repo.continuum.io/pkgs/free/linux-64
                          http://repo.continuum.io/pkgs/free/noarch
                          https://conda.anaconda.org/pydy/linux-64
                          https://conda.anaconda.org/pydy/noarch
                          https://conda.anaconda.org/moorepants/linux-64
                          https://conda.anaconda.org/moorepants/noarch
          package cache : /home/moorepants/miniconda3/pkgs
                          /home/moorepants/.conda/pkgs
       envs directories : /home/moorepants/miniconda3/envs
                          /home/moorepants/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.6.7 Linux/4.15.0-43-generic ubuntu/18.04 glibc/2.27
                UID:GID : 1000:1000
             netrc file : /home/moorepants/.netrc
           offline mode : False

```
</details>

**Comment by ocefpaf** [comment]
I moved it to the `rc` label manually but we need to fix the feedstock to prevent that from happening.

**Comment by TomAugspurger** [comment]
Thanks @ocefpaf. Do you know what needs to be changed? I would have thought that since the `dev` branch has the `rc` label in https://github.com/conda-forge/pandas-feedstock/blob/dev/conda-forge.yml#L9, we'd be OK.

**Comment by ocefpaf** [comment]
> Thanks @ocefpaf. Do you know what needs to be changed? I would have thought that since the `dev` branch has the `rc` label in [/conda-forge.yml@`dev`#L9](https://github.com/conda-forge/pandas-feedstock/blob/dev/conda-forge.yml#L9), we'd be OK.


That used to be the case but there were a few changes in conda-smithy that made `rc` releases more complicated. I'm out of the loop on what needs to be done to get that working again. Maybe @mariusvniekerk or @CJ-Wright knows what needs to be done.

**Comment by TomAugspurger** [comment]
Thanks.

I'm also noticing now that just linux 36 and 27 packages were built: https://anaconda.org/conda-forge/pandas/files?sort=time&sort_order=desc&version=0.24.0rc1 Going to do some more looking into what happened there.

**Comment by CJ-Wright** [comment]
xref: https://github.com/conda-forge/scikit-learn-feedstock/pull/71
