### ISSUE TITLE
Removed version 0.25.0

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/pandas-feedstock#69]
`pandas 0.25.0` had some bugs with indexing that are solved in `0.25.1` but, for some reason, some users are getting the `0.25.0` in their envs. To avoid headaches in a workshop next week I removed the `0.25.0` from the `main` channel.

**Comment by jorisvandenbossche** [comment]
Won't this give problem for people who pinned to 0.25.0 ?

**Comment by ocefpaf** [comment]
Yep. if someone want the buggy version they need to use the `broken` label.

**Comment by TomAugspurger** [comment]
It seems like removing the 0.25.0 package will cause more problems. All our versions have bugs, and we're not removing all the old ones :)

**Comment by TomAugspurger** [comment]
I may misunderstand, but won't `conda install -c
conda-forge::pandas=0.25.0` not work anymore?

**Comment by alimanfoo** [comment]
Hi @ocefpaf, I just wanted to chime in here to say that moving 0.25.0 to the broken label caused us some problems (https://github.com/malariagen/binder/issues/59). Within our team and in our CI environments we use a pinned conda environment file to ensure reproducibility, both between team members and also if we ever need to go back in time to rerun an old analysis. The conda environment files are tied to the analysis code via github, and so we cannot easily change our installation procedure, and reproducibility is broken if we cannot go back and install an environment that had been used to do some work previously.

I appreciate that in this case there was an urgent need to do something for a workshop, and also in this case there are some bugs in pandas 0.25.0 that means it probably should not be used, but as @TomAugspurger says all versions have bugs, and we had used 0.25.0 successfully to run a bunch of analyses without problems. Can I suggest that there is some tightening up of the conditions for moving a package from main to broken? We are really working hard to achieve reproducibility in our team, and depend heavily on conda and conda-forge to achieve that.

**Comment by ocefpaf** [comment]
It is back already. Re-check your CIs.
